import { Person } from "../types/Person";

export const data: Person[] = [
  {
    namn: 'Emery Dorwart',
    tjänstegrad: '75%',
    tjänstetyp: 'Dag/Kväll',
    delegeringar: ['Insulin'],
    grupp: 'Tallhöjden',
    team: 'Blå',
  },
  {
    namn: 'Jakob George',
    tjänstegrad: '80%',
    tjänstetyp: 'Roterande 3-skift',
    delegeringar: ['Låkemedel', 'Insulin'],
    grupp: 'Tallhöjden',
    team: 'Blå',
  },
  {
    namn: 'Maren Passaquindici Arcand',
    tjänstegrad: '100%',
    tjänstetyp: 'Ständig Natt',
    delegeringar: ['Sond'],
    grupp: 'Tallhöjden',
    team: 'Blå',
  },
  {
    namn: 'Justin Donin',
    tjänstegrad: '90%',
    tjänstetyp: 'Dag/Kväll',
    undantagsregler: '2 st',
    delegeringar: [],
    grupp: 'Tallhöjden',
    team: 'Blå',
  },
  {
    namn: 'Marley Vaccaro',
    tjänstegrad: '75%',
    tjänstetyp: 'Dag/Kväll',
    delegeringar: ['Insulin'],
    grupp: 'Tallhöjden',
    team: 'Gul',
  },
  {
    namn: 'Kaylynn Septimus',
    tjänstegrad: '80%',
    tjänstetyp: 'Roterande 3-skift',
    delegeringar: ['Låkemedel', 'Insulin'],
    grupp: 'Tallhöjden',
    team: 'Gul',
  },
  {
    namn: 'Lydia Dias',
    tjänstegrad: '100%',
    tjänstetyp: 'Ständig Natt',
    delegeringar: ['Sond'],
    grupp: 'Tallhöjden',
    team: 'Gul',
  },
  {
    namn: 'Zaire Siphron',
    tjänstegrad: '90%',
    tjänstetyp: 'Dag/Kväll',
    undantagsregler: '2 st',
    delegeringar: [],
    grupp: 'Tallhöjden',
    team: 'Gul',
  },
  {
    namn: 'Desirae Rhiel Madsen',
    tjänstegrad: '75%',
    tjänstetyp: 'Dag/Kväll',
    delegeringar: ['Insulin'],
    grupp: 'Tallhöjden',
    team: 'Grön',
  },
  {
    namn: 'Giana Lipshutz',
    tjänstegrad: '80%',
    tjänstetyp: 'Roterande 3-skift',
    delegeringar: ['Låkemedel', 'Insulin'],
    grupp: 'Tallhöjden',
    team: 'Grön',
  },
  {
    namn: 'Tatiana Carder',
    tjänstegrad: '100%',
    tjänstetyp: 'Ständig Natt',
    delegeringar: ['Sond'],
    grupp: 'Tallhöjden',
    team: 'Grön',
  },
  {
    namn: 'Ashlynn Siphron',
    tjänstegrad: '90%',
    tjänstetyp: 'Dag/Kväll',
    undantagsregler: '2 st',
    delegeringar: [],
    grupp: 'Tallhöjden',
    team: 'Grön',
  },
  {
    namn: 'Desirae Dokidis',
    tjänstegrad: '75%',
    tjänstetyp: 'Dag/Kväll',
    delegeringar: ['Insulin'],
    grupp: 'Tallhöjden',
    team: 'Röd',
  },
  {
    namn: 'Madelyn Schleifer',
    tjänstegrad: '80%',
    tjänstetyp: 'Roterande 3-skift',
    delegeringar: ['Låkemedel', 'Insulin'],
    grupp: 'Tallhöjden',
    team: 'Röd',
  },
  {
    namn: 'Madelyn Rosser',
    tjänstegrad: '100%',
    tjänstetyp: 'Ständig Natt',
    delegeringar: ['Sond'],
    grupp: 'Tallhöjden',
    team: 'Röd',
  },
  {
    namn: 'Skylar Bergson',
    tjänstegrad: '90%',
    tjänstetyp: 'Dag/Kväll',
    undantagsregler: '2 st',
    delegeringar: [],
    grupp: 'Tallhöjden',
    team: 'Röd',
  },
  {
    namn: 'Justin Lubin',
    tjänstegrad: '75%',
    tjänstetyp: 'Dag/Kväll',
    delegeringar: ['Insulin'],
    grupp: 'Älvgården',
    team: 'Gladen',
  },
  {
    namn: 'Alfredo Herwitz',
    tjänstegrad: '80%',
    tjänstetyp: 'Roterande 3-skift',
    delegeringar: ['Låkemedel', 'Insulin'],
    grupp: 'Älvgården',
    team: 'Gladen',
  },
  {
    namn: 'Philip Schleifer',
    tjänstegrad: '100%',
    tjänstetyp: 'Ständig Natt',
    delegeringar: ['Sond'],
    grupp: 'Älvgården',
    team: 'Gladen',
  },
  {
    namn: 'Madelyn George',
    tjänstegrad: '90%',
    tjänstetyp: 'Dag/Kväll',
    undantagsregler: '2 st',
    delegeringar: [],
    grupp: 'Älvgården',
    team: 'Gladen',
  },
  {
    namn: 'Marcus Saris',
    tjänstegrad: '75%',
    tjänstetyp: 'Dag/Kväll',
    delegeringar: ['Insulin'],
    grupp: 'Älvgården',
    team: 'Särlen',
  },
  {
    namn: 'Adison Aminoff',
    tjänstegrad: '80%',
    tjänstetyp: 'Roterande 3-skift',
    delegeringar: ['Låkemedel', 'Insulin'],
    grupp: 'Älvgården',
    team: 'Särlen',
  },
  {
    namn: 'Randy Septimus',
    tjänstegrad: '100%',
    tjänstetyp: 'Ständig Natt',
    delegeringar: ['Sond'],
    grupp: 'Älvgården',
    team: 'Särlen',
  },
  {
    namn: 'Randy Gouse',
    tjänstegrad: '90%',
    tjänstetyp: 'Dag/Kväll',
    undantagsregler: '2 st',
    delegeringar: [],
    grupp: 'Älvgården',
    team: 'Särlen',
  },
  {
    namn: 'Jaydon Batosh',
    tjänstegrad: '100%',
    tjänstetyp: 'Ständig Natt',
    delegeringar: ['Låkemedel', 'Insulin', 'Waran'],
    grupp: 'Ekbacka',
  },
  {
    namn: 'Terry Mango',
    tjänstegrad: '100%',
    tjänstetyp: 'Dag/Kväll',
    delegeringar: ['Låkemedel', 'Insulin', 'Waran'],
    grupp: 'Ekbacka',
  },
  {
    namn: 'Jocelyn Bator',
    tjänstegrad: '90%',
    tjänstetyp: 'Ständig Helg',
    delegeringar: ['Låkemedel', 'Insulin', 'Waran'],
    grupp: 'Ekbacka',
  }
];
